version: "3.3"

services:
  
  bucket:
    image: minio/minio:latest
    container_name: bucket
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - .~/.docker/data:/data
    networks:
      - default 
    restart: always
    command: server /data --console-address ":9001"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "5000:5000"
    volumes:
      - .:/app

    networks:
      - default

    restart: always

networks:
  default:
    external:
      name: mynetwork